### PR TITLE
Symbols search

### PR DESCRIPTION
**Pull request by kwinso**
This PR inroduces feature of asciimath symbol searching mentioned in #11. 

I've parsed the symbols from asciimath-parser library. It adds plugin command called "Insert AsciiMath symbol", which opens search window:
image

After pressing enter, plugin will insert selected symbol. This can be attached to hotkey, I've landed on `Ctrl + M` (for Math)

Possible improvements:
- Add 3rd array member for the symbol which will be the description, also mentioned in #11.

### CODE REVIEW

**Comment by widcardw** [comment]
There are some suggestions that still contain symbols like `$2`, and I think it is a little weird. 

Would it be better to generate such a template:

```
<asciimath>
<LaTeX_template_with_placeholders>
<render_$1_as_"a"_and_$2_as_"b">
```

There are some other syntax sugar such as `ppfx` and `ddfx`, and we can customize the rendered element.

**Comment by kwinso** [comment]
I'm not sure I completely understand what you are trying to say 😓 
Why not just find& replace?

But anyways, I can send a JSON file with $1 & $2 in it so you can try your ideas

**Comment by widcardw** [comment]
I have replaced the json file in my local workspace. I will merge it into the main branch so that you can preview the changes.

**Comment by widcardw** [comment]
image

**Comment by kwinso** [comment]
Unfortunately, I don't have time right now, I'll check it in approx 8 hours :( 
But based on what I see on the screenshot, it's very nice! Thank you!

**Comment by kwinso** [comment]
I'm thinking about adding parameters to the ASCIIMath variation when its placed. 

So instead of `root` it'll be `root a b`. It think it's more intuitive for the user.

**Comment by widcardw** [comment]
Yes, I'll add the "placeholder" for some symbols, such as `\xlongequal`, `root`, `limits` and so on.

image

image

image

**Comment by kwinso** [comment]
Looks good!

**Comment by widcardw** [comment]
I'm wondering which is better, `a, b` or `$1, $2`?

**Comment by kwinso** [comment]
Definitely a and b, dollar ones look like some cryptic syntax

**Pull request merged**
