### PR TITLE
Better migration instruction and bugfix.

### PR DESCRIPTION
**Pull request by kwinso**
This PR fix a bug with converting inline blocks. When converting a formula which has spaces around it:
```text
`$ text $` -> $ text $
```
Resulting block is not recognized by Obsidian, because it requires no spaces around formula for inline blocks.

Also, this PR includes more consice concise notice messages & command names, as well as improved migration notice in the REDAME.

### CODE REVIEW

**Comment by kwinso** [comment]
I'm thinking about renaming "Convert to new syntax" commands to just "Update old notes" or something like this. At this moment we have 4 commands that show up when "convert" is searched:
image

Which is quite overwhelming and prone to user-mistakes. Just image if user will accidentially select "Convert to LaTeX" instead of converting to new syntax :sweat_smile:

**Comment by kwinso** [comment]
I have it ready, but the way. I'll create new PR if you're ok with this.

**Comment by widcardw** [comment]
That may be a problem... I did not think about how to express the real meaning of these commands. Maybe "Update old notes" is better.

**Comment by kwinso** [comment]
Ok, uno momento

**Comment by widcardw** [comment]
> I have it ready, but the way. I'll create new PR if you're ok with this.

Okay, just go ahead. I was too excited with the changes and did not even wait for your response.. Sorry...

**Comment by kwinso** [comment]
That's all right! <3

**Pull request merged**
