### PR TITLE
Distinct migration commands & refactoring.

### PR DESCRIPTION
**Pull request by sotnii**

### CODE REVIEW

**Comment by kwinso** [comment]
Please, wait a second, I wan't to make one more commit with refactored code. No functionality added, just split to files & rearrange functions

**Comment by widcardw** [comment]
Ok, I'll wait until you've confirmed that everything is done.

**Comment by kwinso** [comment]
I think, this is all I've wanted to do :thinking:

**Comment by widcardw** [comment]
There's some problem with the name of  "Update old asciimath (entire vault)". I'll fix it within this PR.

**Comment by kwinso** [comment]
No problem!

**Comment by kwinso** [comment]
Also, there's a problem with `asciimath-parser/index` import, it should be just `asciimath-parser`. I'll let you fix it, otherwise my commit may cause merging issues.

**Comment by widcardw** [comment]
Yes, I've noticed it. And I am recording a new screenshot for the commands.

**Pull request merged**
